#include <stdio.h>
#include <string.h>

#include <dtcore/dterr.h>
#include <dtcore/dtguid.h>
#include <dtcore/dtunittest.h>

// -------------------------------------------------------------------------
static dterr_t*
test_dtguid_zero(void)
{
    dterr_t* dterr = NULL;
    dtguid_t guid;
    dtguid_zero(&guid);

    DTUNITTEST_ASSERT_TRUE(dtguid_is_zero(&guid));

cleanup:
    if (dterr != NULL)
    {
        dterr = dterr_new(DTERR_ASSERTION, __LINE__, __FILE__, __func__, dterr, "unexpected assertion failure");
    }
    return dterr;
}

// -------------------------------------------------------------------------
static dterr_t*
test_dtguid_copy(void)
{
    dterr_t* dterr = NULL;
    dtguid_t a, b;
    dtguid_zero(&a);
    a.bytes[0] = 1;
    a.bytes[15] = 255;

    dtguid_copy(&b, &a);
    DTUNITTEST_ASSERT_TRUE(dtguid_is_equal(&a, &b));

cleanup:
    if (dterr != NULL)
    {
        dterr = dterr_new(DTERR_ASSERTION, __LINE__, __FILE__, __func__, dterr, "unexpected assertion failure");
    }
    return dterr;
}

// -------------------------------------------------------------------------
static dterr_t*
test_dtguid_cmp(void)
{
    dterr_t* dterr = NULL;
    dtguid_t a, b;
    dtguid_zero(&a);
    dtguid_zero(&b);

    a.bytes[5] = 1;
    b.bytes[5] = 2;

    DTUNITTEST_ASSERT_TRUE(dtguid_cmp(&a, &b) < 0);
    DTUNITTEST_ASSERT_TRUE(dtguid_cmp(&b, &a) > 0);

cleanup:
    if (dterr != NULL)
    {
        dterr = dterr_new(DTERR_ASSERTION, __LINE__, __FILE__, __func__, dterr, "unexpected assertion failure");
    }
    return dterr;
}

// -------------------------------------------------------------------------
static dterr_t*
test_dtguid_generate_sequential(void)
{
    dterr_t* dterr = NULL;
    dtguid_t a, b;
    dtguid_generate_sequential(&a);
    dtguid_generate_sequential(&b);

    DTUNITTEST_ASSERT_TRUE(!dtguid_is_zero(&a));
    DTUNITTEST_ASSERT_TRUE(!dtguid_is_zero(&b));
    DTUNITTEST_ASSERT_TRUE(dtguid_cmp(&a, &b) < 0);

cleanup:
    if (dterr != NULL)
    {
        dterr = dterr_new(DTERR_ASSERTION, __LINE__, __FILE__, __func__, dterr, "unexpected assertion failure");
    }
    return dterr;
}

// -------------------------------------------------------------------------
static dterr_t*
test_dtguid_generate_from_string(void)
{
    dterr_t* dterr = NULL;
    dtguid_t guid;
    dtguid_generate_from_string(&guid, "sensor-node-42");

    // Make sure it's not zero
    DTUNITTEST_ASSERT_TRUE(!dtguid_is_zero(&guid));

    // Convert to string for checking prefix and compliance
    char buffer[37];
    dtguid_to_string(&guid, buffer, sizeof(buffer));

    // Check string is that generated by a python script
    DTUNITTEST_ASSERT_EQUAL_STRING(buffer, "f88461fa-dae0-356e-b4f8-f6b35785da69");

    // Check version field (position 14, 0-based): must be '3'
    DTUNITTEST_ASSERT_TRUE(buffer[14] == '3');

    // Check variant field (position 19): must be one of '8', '9', 'a', or 'b'
    DTUNITTEST_ASSERT_TRUE(strchr("89ab", buffer[19]) != NULL);

cleanup:
    if (dterr != NULL)
    {
        dterr = dterr_new(DTERR_ASSERTION, __LINE__, __FILE__, __func__, dterr, "unexpected assertion failure");
    }
    return dterr;
}

// -------------------------------------------------------------------------
static dterr_t*
test_dtguid_to_string(void)
{
    dterr_t* dterr = NULL;
    dtguid_t guid;
    dtguid_zero(&guid);
    guid.bytes[0] = 0x12;
    guid.bytes[1] = 0x34;
    guid.bytes[2] = 0x56;
    guid.bytes[3] = 0x78;
    guid.bytes[4] = 0x9a;
    guid.bytes[5] = 0xbc;
    guid.bytes[6] = 0xde;
    guid.bytes[7] = 0xf0;
    guid.bytes[8] = 0x12;
    guid.bytes[9] = 0x34;
    guid.bytes[10] = 0x56;
    guid.bytes[11] = 0x78;
    guid.bytes[12] = 0x9a;
    guid.bytes[13] = 0xbc;
    guid.bytes[14] = 0xde;
    guid.bytes[15] = 0xf0;

    char buffer[37];
    dtguid_to_string(&guid, buffer, sizeof(buffer));

    const char* expected = "12345678-9abc-def0-1234-56789abcdef0";
    DTUNITTEST_ASSERT_EQUAL_STRING(buffer, expected);

cleanup:
    if (dterr != NULL)
    {
        dterr = dterr_new(DTERR_ASSERTION, __LINE__, __FILE__, __func__, dterr, "unexpected assertion failure");
    }
    return dterr;
}

// -------------------------------------------------------------------------
// suite runner
void
test_dtguid(DTUNITTEST_SUITE_ARGS)
{
    DTUNITTEST_RUN_TEST(test_dtguid_zero);
    DTUNITTEST_RUN_TEST(test_dtguid_copy);
    DTUNITTEST_RUN_TEST(test_dtguid_cmp);
    DTUNITTEST_RUN_TEST(test_dtguid_generate_sequential);
    DTUNITTEST_RUN_TEST(test_dtguid_to_string);
    DTUNITTEST_RUN_TEST(test_dtguid_generate_from_string);
}
