site_name: dtcore Library
site_url: https://david-erb.github.io/dtcore/
theme:
  name: material
  features:
  - navigation.sections
  - navigation.indexes
  - content.code.copy
plugins:
- search
markdown_extensions:
- admonition
- toc
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.snippets:
    check_paths: true
    base_path: .
- tables
extra_css:
- stylesheets/extra.css
nav:
- Home: index.md
- Demos:
  - Demos Overview: demos/index.md
  - demo_buffer: demos/demo_buffer.md
  - demo_error: demos/demo_error.md
  - demo_hello: demos/demo_hello.md
  - demo_random: demos/demo_random.md
- Function Groups:
  - function_groups/index.md
  - Memory Management:
    - dtbuffer: function_groups/dtbuffer.md
    - dtheaper: function_groups/dtheaper.md
    - dtledger: function_groups/dtledger.md
    - dtpackx: function_groups/dtpackx.md
  - Logging and Error Handling:
    - dterr: function_groups/dterr.md
    - dteventlogger: function_groups/dteventlogger.md
    - dtlog: function_groups/dtlog.md
  - Facade/Vtables:
    - dtguidable: function_groups/dtguidable.md
    - dtobject: function_groups/dtobject.md
    - dtpackable: function_groups/dtpackable.md
    - dtrandomizer: function_groups/dtrandomizer.md
    - dtvtable: function_groups/dtvtable.md
  - Data Structures:
    - dtarray_float: function_groups/dtarray_float.md
    - dtarray_int32: function_groups/dtarray_int32.md
    - dtkvp: function_groups/dtkvp.md
    - dtguid: function_groups/dtguid.md
    - dtringfifo: function_groups/dtringfifo.md
    - dtchunker: function_groups/dtchunker.md
    - dtflipper: function_groups/dtflipper.md
  - Mathematical:
    - dtrandomizer_browngrav: function_groups/dtrandomizer_browngrav.md
    - dtrandomizer_uniform: function_groups/dtrandomizer_uniform.md
    - dtlcg: function_groups/dtlcg.md
  - Unit Testing:
    - dtunittest: function_groups/dtunittest.md
  - Miscellaneous:
    - dtstr: function_groups/dtstr.md
    - dtbytes: function_groups/dtbytes.md
    - dtwallclock: function_groups/dtwallclock.md
    - dttrap: function_groups/dttrap.md
- Developer Guides:
  - guides/index.md
  - Quick Start: guides/quick_start.md
  - Running Applications: guides/running_apps.md
  - Repository structure: guides/repository_structure.md
  - Design principles: guides/design_principles.md
  - Structured error handling: guides/errors.md
  - Virtual-table pattern: guides/vtables.md
  - Cross-wire constants: guides/constants.md
